# Generated by Django 4.1 on 2022-09-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemwishlist",
            name="item_name",
            field=models.CharField(max_length=255),
        ),
    ]
