# Generated by Django 4.1 on 2022-11-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_alter_itemwishlist_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemwishlist",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
